#### docker-compose app inizio
version: '2'
services:
  my-smart-hommy-client:
    image: ${DOCKER_REGISTRY_URL}paolotti/iot/mysmarthommy/client:${CLIENT_TAG}
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${CLIENT_PORT_80_MAPPING_TO}:80
    restart: unless-stopped
  my-smart-hommy-backend:
    image: ${DOCKER_REGISTRY_URL}paolotti/iot/mysmarthommy/backend:${BACKEND_TAG}
    ports:
      - ${BACKEND_PORT_8080_MAPPING_TO}:8080
    restart: unless-stopped
  my-smart-hommy-mocks:
    image: ${DOCKER_REGISTRY_URL}paolotti/iot/mysmarthommy/mocks:${MOCKS_TAG}
    ports:
      - ${MOCKS_PORT_3001_MAPPING_TO}:3001
    restart: unless-stopped
# docker-compose -f app.docker.compose.yml pull  && docker-compose -f app.docker.compose.yml up -d  && docker ps
# docker-compose -f app.docker.compose.yml pull  && docker-compose -f app.docker.compose.yml up -d --force-recreate && docker ps